### ISSUE TITLE
Am I doing something wrong here?

### ISSUE THREAD

**Issue by Tasdv** [woctezuma/steam-market#20]
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\steam-market-master\market_listing.py", line 75, in <module>
    def parse_item_type_no_from_script(last_script: str) -> [int | None]:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by woctezuma** [comment]
I have added function annotations for type hinting recently. The [`typing` library](https://docs.python.org/3/library/typing.html) is supported starting with Python 3.5 (and later versions). Do you have a version of Python earlier than 3.5?

**Comment by woctezuma** [comment]
Actually, [`PEP 604 -- Allow writing union types as X | Y`](https://www.python.org/dev/peps/pep-0604/) requires Python 3.10.

**Comment by Tasdv** [comment]
So I must use python 3.10?

**Comment by Tasdv** [comment]
I'm running python 3.9.9 right now.

**Comment by woctezuma** [comment]
Okay, thank you! So that is because of PEP 604 which is only supported by Python 3.10.

**Comment by Tasdv** [comment]
Where do the final results appear when using the market_arbitrage_with_foil_cards.py

**Comment by woctezuma** [comment]
There are printed to the console.
