### ISSUE TITLE
Dk what happened

### ISSUE THREAD

**Issue by Tasdv** [woctezuma/steam-market#22]
[X]     Unreliable goo details for

**Comment by Tasdv** [comment]
Or [?]     Unknown goo value for

**Comment by woctezuma** [comment]
These are warnings: they don't block the program. They appear here:
https://github.com/woctezuma/steam-market/blob/0ce25a0493b966ce30e134bd9b68cc1fd86ad59a/market_arbitrage_with_foil_cards.py#L716-L729
