### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Tasdv** [woctezuma/steam-market#23]
No matter what I do, the program always replies " Unreliable goo details for " for every single goo detail.

**Comment by woctezuma** [comment]
There can be a lot of unreliable goo details, but there should be a lot of reliable ones as well.

Maybe Valve changed something in the past few years. If so, try to use previously collected and saved goo details.

**Comment by Tasdv** [comment]
None of the goo details worked, I have created new ones already, same problem.

**Comment by Tasdv** [comment]
I redownloaded the program again and the same thing has occured, new goo details don't work either.

**Comment by woctezuma** [comment]
Does the program terminate early?

Even if you don't have new goo details, you should be able to get results based on the previously collected ones at:
> https://github.com/woctezuma/steam-market/blob/master/data/goo_details_for_foil_cards.json

**Comment by Tasdv** [comment]
The program doesn't terminate early, it finishes without terminating.

**Comment by Tasdv** [comment]
[log.txt](https://github.com/woctezuma/steam-market/files/7785179/log.txt)

**Comment by Tasdv** [comment]
The error logs

**Comment by woctezuma** [comment]
> [log.txt](https://github.com/woctezuma/steam-market/files/7785179/log.txt)

I cannot see the logs.

**Comment by woctezuma** [comment]
> [log.txt](https://github.com/woctezuma/steam-market/files/7785179/log.txt)

I believe that there was no arbitrage.

It is also possible that the program terminated early, but it seems to have reached the final step and there is no sign of any error.
