### ISSUE TITLE
Item type not found for 753-Sack of Gems

### ISSUE THREAD

**Issue by Tasdv** [woctezuma/steam-market#24]
Item type not found for 753-Sack of Gems

**Comment by woctezuma** [comment]
This is not an error. This is expected, because a sack of gems is not a foil card.

**Comment by Tasdv** [comment]
It auto stops the program tho.

**Comment by Tasdv** [comment]
Nevermind, I accidentally deleted part of the code.

**Comment by Tasdv** [comment]
All the goo details still show up as unreliable tho

**Comment by woctezuma** [comment]
A lot of the goo details will show as unreliable, but some of them should be reliable. #22, #23

Unfortunately, that is due to Valve's way of obfuscating access to goo details with unreliable item IDs.
