### ISSUE TITLE
New rate-limits for itemordershistogram?

### ISSUE THREAD

**Issue by woctezuma** [woctezuma/steam-market#27]
There is a recent issue with rate-limits on the Steam Market.

![Rate-limits](https://i.imgur.com/Bo7WMyt.png)

![Error](https://i.imgur.com/kahO8Bm.png)

![Market](https://i.imgur.com/2w144Db.png)

**Comment by sueskind** [comment]
As said in the posted screenshot, there is very little discussion about this rate limit increase, but it seems like you found a workaround.

Can you tell me how you got around this limit? Is this limit (10 requests/h) the same when being logged in/out?

**Comment by sueskind** [comment]
Thanks for the reply, it seems that the limits are as follows:

When logged **out**:
- 10-25 requests allowed, then rate limit is hit

When logged **in**:
- Infinite requests for the same `nameid` allowed
- 10 requests for different `nameid`s allowed until rate limit is hit.

The rate limit seems to be a longer "cooldown" than 1h in both cases.

It looks like a tradeoff they came up with at Valve to limit scraping but not interfere too much with normal usage.

**Comment by woctezuma** [comment]
Thank you! That is interesting!

Public information about rate limits are hard to find, so it is nice to read about the results of your experiments! ❤️
