### ISSUE TITLE
Booster Packs not created

### ISSUE THREAD

**Issue by TCarneiro91** [woctezuma/steam-market#47]
Hey, I am messing around with your project, and I can't update the games that we can craft cards (booster_game_creator.txt)

It always picks up games that are not in the list.
Is this project still being maintained?

**Comment by TCarneiro91** [comment]
I followed all the steps, I have updated the file with the augmented steam extension, and made sure that the format was exactly the same as your instructions. Somehow the results are negative.

Also, is it possible to automate the crafting, and selling cards? I am not getting there somehow

**Comment by woctezuma** [comment]
> Also, is it possible to automate the crafting, and selling cards? I am not getting there somehow

You could look into [ASF plugins](https://github.com/Citrinate/BoosterManager) or Python modules such as [`steampy`](https://github.com/bukson/steampy#market-methods).
