### ISSUE TITLE
Some game titles generate a syntax error on output

### ISSUE THREAD

**Issue by daemond-dev** [woctezuma/steam-market#79]
When running any of the main scripts, some titles seem to generate a syntax error, possibly due to how their name is saved when pulled from Steam which might be including an unnecessary escape character.

![image](https://github.com/user-attachments/assets/86001478-37dd-4cf4-aaed-ad09fb47064f)

Currently using Python 3.13. Happy to provide any additional info, if necessary.

**Comment by woctezuma** [comment]
These are syntax warnings. I believe you are correct that they must be due to titles with some unusual characters.

I have encountered these warnings as well in the past. However, I have not investigated more, as they were not blocking.
